### ISSUE TITLE
Update info about fonts

### ISSUE THREAD

**Issue by dvaeversted** [HTML24/HTML5-template#14]
Since we now have our internal tool for generating font kits, this should be reflected in the README.

http://html24-dev.dk/dennis/fonttool/

**Comment by dvaeversted** [comment]
@DKvistgaard, i think that you should specify that the section about re-ordering the font-face css, only applies if you are NOT using our internal tool.

**Comment by DKvistgaard** [comment]
I thought I had done that, but I'll make it more clear then. :)
