### ISSUE TITLE
Remove contents of title tag

### ISSUE THREAD

**Issue by dvaeversted** [HTML24/HTML5-template#15]
Since people seem to forget to change the title on the template.

I think we should remove the content of the title tag, this way we are atleast not gonna push out a solution that says "HTML24 Template" in the browser title.
Or as the title on a facebook share.

I know we should catch this in QA, but i also believe it has slipped through quite a few times especially on facebook apps or mobile versions of a site.

**Comment by DKvistgaard** [comment]
Agreed, I have noticed that quite a few times aswell. But I don't think we should complete remove it, because it should also serve as a reminder, that people need to write a page title.
What about doing something like this:
`<title><!-- THE PAGE TITLE --></title>`

**Comment by dvaeversted** [comment]
That could work equally well.

As long as nothing is displayed in the browser.

On 2013-06-26T10:01:41 CEST, DKvistgaard wrote:

> Agreed, I have noticed that quite a few times aswell. But I don't
> think we should complete remove it, because it should also serve as a
> reminder, that people need to write a page title.
> What about doing something like this:
> |<title></title>|
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HTML24/HTML5-template/issues/15#issuecomment-20032278.

## 

Best Regards,

_Dennis Væversted_

dv@html24.net mailto:dv@html24.net
twitter.com/@D_Vaeversted http://twitter.com/@D_Vaeversted
Phone: +45 4241 6160
Web: www.html24.dk http://www.html24.dk
Customers: twentyfour.html24.dk http://twentyfour.html24.dk
Newsletter: Tips, tricks og nyheder på dansk!
http://www.html24.dk/#newsletter

HTML24 ApS | Prags Boulevard 49E, 3. sal - Opgang 11 | 2300 København S
Creating awesome code to more than 250 companies in Scandinavia.

All projects with HTML24 ApS are regulated according to our Terms and
Conditions - Fetch Danish Terms and Conditions here
http://www.html24.dk/standardbetingelser.pdf.
Alle projekter og aftaler med HTML24 ApS er reguleret af vores
standardbetingelser - Hent standardbetingelser her
http://www.html24.dk/standardbetingelser.pdf.

**Comment by tomgud** [comment]
+1
