### ISSUE TITLE
Separate reset stylesheet

### ISSUE THREAD

**Issue by DKvistgaard** [HTML24/HTML5-template#7]
I was thinking about making a separate stylesheet for all the CSS resets. So you didn't have to scroll in the CSS file before coding to begin with. 
Then people might also start to notice the default stylings for header-tags, which they should change to fit their current project. 
Maybe we could even use the Normalize.css as Bo talked about in the other issue.

What do you guys think about this?

**Comment by dvaeversted** [comment]
I like the idea of the Normalize.css

Having some sane standard definitions.

On 2012-10-18T10:58:07 CEST, DKvistgaard wrote:

> I was thinking about making a separate stylesheet for all the CSS
> resets. So you didn't have to scroll in the CSS file before coding to
> begin with.
> Then people might also start to notice the default stylings for
> header-tags, which they should change to fit their current project.
> Maybe we could even use the Normalize.css as Bo talked about in the
> other issue.
> 
> What do you guys think about this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HTML24/HTML5-template/issues/7.

## 

Best Regards,

_Dennis Væversted_

dv@html24.net mailto:dv@html24.net
Phone: +45 4241 6160
Web: www.html24.dk http://www.html24.dk
Customers: twentyfour.html24.dk http://twentyfour.html24.dk
Newsletter: HTML24 News 'n' updates!
http://html24.us2.list-manage1.com/subscribe?u=b32c92f9b30a1cdf5ecf6c96a&id=359218cc47

HTML24 ApS | Prags Boulevard 49, 3. sal - Opgang 11 | 2300 København S
Delivering awesome code to more than 200 companies in Scandinavia.

All projects with HTML24 ApS are regulated according to our Terms and
Conditions - Fetch Danish Terms and Conditions here
http://www.html24.dk/standardbetingelser.pdf.
Alle projekter og aftaler med HTML24 ApS er reguleret af vores
standardbetingelser - Hent standardbetingelser her
http://www.html24.dk/standardbetingelser.pdf.

**Comment by JonPer** [comment]
Cool idea. We could just use the @import url("reset.css"); in the start of the main.css.

Should we make a css files called fonts aswell? - In that way we only have css for elements in the main.css

**Comment by DKvistgaard** [comment]
Me and Jackie talked about the import feature, and we decided that it might not be a good idea to use it. It doesn't do parallel import and isn't good for performance. So if we should do it, then we might as well include two separate files in the html file.

**Comment by JackieNagel** [comment]
import us cool - BUT - there's performance issues attached to this:
http://www.stevesouders.com/blog/2009/04/09/dont-use-import/

In some browsers, namely IE, it breaks parallel download which results in longer transfer times, which in the end, leads to slower page rendition :-)

**Comment by JonPer** [comment]
Okay - Then I actually don't see the idea of having seperate files. Maybe in development, but when the site is running live, it should only be running with one css file.

**Comment by JackieNagel** [comment]
+1

## 

Jackie Nagel
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
