### ISSUE TITLE
Add note about order of fonts

### ISSUE THREAD

**Issue by dvaeversted** [HTML24/HTML5-template#8]
When you generate fonts with the different "typekit" services, they are not necessarily in correct order.
Chrome had/has an issue where fonts will look blurry, if the order of the url()'s are not in a specific order.

A bit of information: http://www.adtrak.co.uk/blog/font-face-chrome-rendering/

**Comment by DKvistgaard** [comment]
Closed with 651b7ff2d61449cf616b69ea191107e163760018
