### ISSUE TITLE
Link outlines

### ISSUE THREAD

**Issue by dvaeversted** [HTML24/HTML5-template#9]
A dotted outline appears atleast in firefox, on a tags.

Should this be removed ?

**Comment by DKvistgaard** [comment]
I don't think we should remove it, since it's important for accessibility. If we remove it though, then we should make a styling for the `:focus` on the a tags. Maybe make it the same as the `:hover`?

**Comment by DKvistgaard** [comment]
Fixed with 8c262e6d577b9bbef5f61c85514f1f531f64350e
